Fixed ftb backups

diff --git a/backups/backup-ftb-monster b/backups/backup-ftb-monster
--- a/backups/backup-ftb-monster
+++ b/backups/backup-ftb-monster
@@ -24,42 +24,38 @@ DIR=`dirname $(readlink -f "$0")`
 
 clock () { echo -n "[`date +%H:%M:%S`] "; }
 function rsync-check {
-	[[ $1 == 0 ]] && echo `clock`"Rsync finished Successfully"
-	[[ $1 == 24 ]] && echo `clock`"Rsync finished with some ignorable errors (some files vanished before they could be transferred)" && 1=0
-	[[ $1 != 0 ]] && echo `clock`"Rsync failed with error code $1, backup for $DATE will be deleted."
+	case $1 in
+		0)
+			echo `clock`"Rsync finished Successfully"
+			;;
+		24)
+			echo `clock`"Rsync finished with some ignorable errors (some files vanished before they could be transferred)"
+			;;
+		*)
+			echo `clock`"Rsync failed with error code $1, backup for $DATE will be deleted."
+			;;
+	esac
 	return $1
 }
 
-function remove-backup {
-	echo `clock`"Clean Up: $1 backup has been detected as over 48 hours old"
-	if [[ -z "$cleanup" ]]
-	then
-		echo `clock`"Clean Up: An error has occurred during cleanup; $1 will NOT be deleted"
-	else
-		if [ -f $cleanup ]
-		then
-			echo `clock`"Clean Up: Clean Up is enabled; Deleting $1"
-			rm -rf $1
-		else
-			echo `clock`"Clean Up: Clean Up is disabled; $1 will NOT be deleted."
-		fi
-	fi
+function exit-cleanup {
+	[[ -n $rsyncfailed ]] && rm -rf $backup_current
+	rm -f $LOCK
 }
 
 LOG="/var/log/$(basename $0).log"
 LOCK="/run/lock/$(basename $0)"
-
 exec > $LOG 2>&1
 
 exec 200>$LOCK
+
 if flock -xn 200; then
-	trap "rm $LOCK" SIGINT SIGTERM
+	trap exit-cleanup 0 SIGINT SIGTERM
 	
 	# Instance variables
 	backup_current="$BACKUPDIR/$DATE"
 	rsyncopts="-aHAX"
-	cleanup=$BACKUPDIR/_cleanup
-	screenname=$(grep FTBUSER=ftb-monster /etc/conf.d/ftb-monster-server|cut -d'=' -f2)
+	screenname=$(grep FTBUSER=ftb-monster /etc/conf.d/ftb-monster|cut -d'=' -f2)
 
 	if [ -e $backup_current ]
 	then
@@ -86,24 +82,22 @@ if flock -xn 200; then
 		inc=""
 	fi
 
-	rsync $rsyncopts --stats --delete $inc $target "$backup_current"
-	rsync-check $?
-	[[ $? != 0 ]] && rm -rf "$backup_current" || touch "$backup_current"
+	rsync $rsyncopts --rsync-path='nice rsync' --stats --delete --exclude=dynmap $inc $TARGET "$backup_current"
+	rc=$?
+	rsync-check $rc
+
+	if [[ $rc != 0 ]] && [[ $rc != 24 ]]; then
+		rsyncfailed=true
+	else
+		touch "$backup_current"
+	fi
 
 	echo -n `clock`"Syncing filesystems... "
 	sync; check $?
 
-	if [ -f $cleanup ]
-	then
-		echo `clock`"Clean Up: Starting..."
-		for i in `find $BACKUPDIR/20* -maxdepth 0 -type d -mtime +2`
-		do
-			remove-backup $i
-		done
-		echo `clock`"Clean Up: Completed"
-	else
-		echo `clock`"Clean Up: Disabled; skipping..."
-	fi
+	echo `clock`"Clean Up: Starting..."
+	find $BACKUPDIR/20* -maxdepth 0 -type d -mtime +2 -delete
+	echo `clock`"Clean Up: Completed"
 else
 	echo "$DATE Lock file $LOCK present. Aborting"
 fi
