rc 32 from mount can mean it either failed to mount, or it was already mounted. best to abort

diff --git a/backups/removable-backup b/backups/removable-backup
--- a/backups/removable-backup
+++ b/backups/removable-backup
@@ -50,18 +50,13 @@ if flock -xn 200; then
 	mkdir -p "${BACKUPDIR}"
 	mount ${DEVICE} ${BACKUPDIR}
 	return=$?
-	if [ ${return} -ne 0 ]
+	if [[ ${return} -ne 0 ]]
 	then
-		if [ ${return} -eq 32 ]
-		then
-			echo "`clock` Drive is already mounted. Continuing backup..."
-		else
-			echo "`clock` Mounting failed; aborting backup"
-			exit 1
-		fi
+		echo "`clock` Mounting failed; aborting backup"
+		exit 1
 	fi
 
-	if [ -f /tmp/donotbackup ]
+	if [[ -f /tmp/donotbackup ]]
 	then
 		echo "`clock` Skipping backup due to /tmp/donotbackup existing"
 		exit 1
