Changed from cat to /bin/cat

diff --git a/other/bloodwood-update-arch-pxe b/other/bloodwood-update-arch-pxe
--- a/other/bloodwood-update-arch-pxe
+++ b/other/bloodwood-update-arch-pxe
@@ -27,7 +27,7 @@ echo -n "Mounting //abachi/OSes... "
 mount -o credentials=~/.smbcreds //abachi/OSes /mnt/OSes > /tmp/error 2>&1
 rc=$?
 check $rc
-[[ $rc != 0 ]] && echo "Error: $(cat /tmp/error)" && exit 1
+[[ $rc != 0 ]] && echo "Error: $(/bin/cat /tmp/error)" && exit 1
 
 if [[ $XBMC == "true" ]]
 	iso=$(ls -1t /mnt/OSes/x86/Arch|grep xbmc|head -1)
@@ -39,7 +39,7 @@ echo -n "Mounting arch ISO ($iso)... "
 mount /mnt/OSes/x86/Arch/$iso /mnt/ISO > /tmp/error 2>&1
 rc=$?
 check $rc
-[[ $rc != 0 ]] && echo "Error: $(cat /tmp/error)" && exit 1
+[[ $rc != 0 ]] && echo "Error: $(/bin/cat /tmp/error)" && exit 1
 
 echo "Copying files..."
 rsync -a --delete /mnt/ISO/ /srv/nfs/$PATH/
