Fixed error checking to handle errors more nicely

diff --git a/other/bloodwood-update-arch-pxe b/other/bloodwood-update-arch-pxe
--- a/other/bloodwood-update-arch-pxe
+++ b/other/bloodwood-update-arch-pxe
@@ -12,18 +12,18 @@ function check {
 
 
 echo -n "Mounting //abachi/OSes... "
-umount /mnt/OSes > /dev/null
-mount -o credentials=~/.smbcreds //abachi/OSes /mnt/OSes
+umount /mnt/OSes > /dev/null 2>&1
+mount -o credentials=~/.smbcreds //abachi/OSes /mnt/OSes > /tmp/error 2>&1
 rc=$?
 check $rc
-[[ $rc != 0 ]] && exit 1
+[[ $rc != 0 ]] && echo "Error: $(cat /tmp/error)" && exit 1
 
 echo -n "Mounting arch ISO... "
-umount /mnt/ISO > /dev/null
-mount /mnt/OSes/x86/Arch/custom.iso /mnt/ISO
+umount /mnt/ISO > /dev/null 2>&1
+mount /mnt/OSes/x86/Arch/custom.iso /mnt/ISO > /tmp/error 2>&1
 rc=$?
 check $rc
-[[ $rc != 0 ]] && exit 1
+[[ $rc != 0 ]] && echo "Error: $(cat /tmp/error)" && exit 1
 
 echo "Copying files..."
 rsync -a --delete /mnt/ISO/ /srv/nfs/arch/
