Added check if package downloaded correctly

diff --git a/other/build-new-packages b/other/build-new-packages
--- a/other/build-new-packages
+++ b/other/build-new-packages
@@ -28,27 +28,31 @@ do
 	dlaur $list > /dev/null
 	while read package
 	do
-		cd $tmp/$curarch
-		grep -E "^\s*(pkgver|pkgrel|epoch|pkgname)=" $tmp/$curarch/$package/PKGBUILD >> $tmp/$curarch/$package/temp
-		. $tmp/$curarch/$package/temp
-		[[ $? != 0 ]] && echo "An error has occurred while parsing $package. Aborting..." && exit 1
-		[[ ! -z "$epoch" ]] && pkgver="$epoch:$pkgver"
-		packageversion="$pkgname-$pkgver-$pkgrel"
-		unset pkgname pkgver pkgrel arch epoch
-		if find $REPO/$curarch -maxdepth 1 | grep -q "$packageversion"
-		then
-			echo "$curarch/$package is already up-to-date. Skipping..." > /dev/null
-		else
-			echo "$curarch/$package is out of date. Building..."
-			cd $tmp/$curarch/$package
-			yes ""|makepkg -rcfs --asroot > $tmp/$curarch/$package/makepkg.log 2>&1
-			if [[ $? != 0 ]]; then
-				echo "An error occurred during build... makepkg output will display in 3 seconds"
-				sleep 3
-				cat $tmp/$curarch/$package/makepkg.log
+		if [[ -d "$tmp/$curarch/$package" ]]; then
+			cd $tmp/$curarch
+			grep -E "^\s*(pkgver|pkgrel|epoch|pkgname)=" $tmp/$curarch/$package/PKGBUILD >> $tmp/$curarch/$package/temp
+			. $tmp/$curarch/$package/temp
+			[[ $? != 0 ]] && echo "An error has occurred while parsing $package. Aborting..." && exit 1
+			[[ ! -z "$epoch" ]] && pkgver="$epoch:$pkgver"
+			packageversion="$pkgname-$pkgver-$pkgrel"
+			unset pkgname pkgver pkgrel arch epoch
+			if find $REPO/$curarch -maxdepth 1 | grep -q "$packageversion"
+			then
+				echo "$curarch/$package is already up-to-date. Skipping..." > /dev/null
 			else
-				mv $tmp/$curarch/$package/${packageversion}*.pkg* $REPO/$curarch
+				echo "$curarch/$package is out of date. Building..."
+				cd $tmp/$curarch/$package
+				yes ""|makepkg -rcfs --asroot > $tmp/$curarch/$package/makepkg.log 2>&1
+				if [[ $? != 0 ]]; then
+					echo "An error occurred during build... makepkg output will display in 3 seconds"
+					sleep 3
+					cat $tmp/$curarch/$package/makepkg.log
+				else
+					mv $tmp/$curarch/$package/${packageversion}*.pkg* $REPO/$curarch
+				fi
 			fi
+		else
+			echo "Unable to find package $package. Skipping..."
 		fi
 	done < $REPO/$curarch/$PACKAGES
 done
