Fixed error in initial checks; moved check function to call the new library; ensured aborted backup message will be included in logs; cleaned up code

diff --git a/backup-system-incremental b/backup-system-incremental
--- a/backup-system-incremental
+++ b/backup-system-incremental
@@ -9,16 +9,27 @@ BACKUPDIR=/raid/shares/backups/Linux
 DATE=`date +%Y-%m-%d`
 LOG="/var/log/system-backup-incremental.log"
 
+# Initial checks
 if [[ $EUID -ne 0 ]]; then
 	echo "This script must be run as root" 1>&2
 	exit 1
 fi
 
-if [ $# == 1 ] ; then
+if [ $# != 1 ] ; then
 	echo "${DATE}You must specify a single machine to make an incremental backup of."
 	exit 1
 fi
 
+# Functions
+. lib/check
+clock () { echo -n "[`date +%H:%M:%S`] "; }
+function rsync-check {
+	[[ $1 == 0 ]] && echo `clock`"Rsync failed with error code $1, backup for ${DATE} may be corrupt."
+	[[ $1 != 0 ]] && echo `clock`"Rsync finished Successfully"
+}
+
+
+exec > >(tee ${LOG})
 LOCK=/run/lock/`basename $0`
 exec 200>${LOCK}
 if flock -xn 200; then
@@ -28,21 +39,8 @@ if flock -xn 200; then
 	backup_current="${backup_host_dir}/${DATE}"
 	exclude=${backup_current}/_exclude
 
-	clock () { echo -n "[`date +%H:%M:%S`] "; }
-	function check {
-		[[ $1 == 0 ]] && echo -e "[\e[1;32mOK\e[00m]"
-		[[ $1 != 0 ]] && echo -e "[\e[1;31mFAILED\e[00m]\nSee ${LOG} for more details"
-	}
-
-	function rsync-check {
-	[[ $1 == 0 ]] && echo `clock`"Rsync failed with error code $1, backup for ${DATE} may be corrupt."
-	[[ $1 != 0 ]] && echo `clock`"Rsync finished Successfully"
-	}
-
 
 	echo -e "-----------------------| Starting backup of ${backup_host} at `date +%Y-%m-%d\ %H:%M:%S` |-----------------------" > ${LOG}
-	exec > >(tee ${LOG})
-
 
 	echo `clock`"Starting backup of ${backup_host} to ${backup_current}"
 	
@@ -56,19 +54,20 @@ if flock -xn 200; then
 	if [ ${backup_previous} ]
 	then
 		echo `clock`"Using ${backup_previous} for hardlinks"
-		rsync -a --stats --delete --delete-excluded --exclude-from=${exclude} --link-dest=${backup_previous} /tmp/${HOST} ${backup_current}
+		rsync -a --stats --delete --delete-excluded --exclude-from=${exclude} \
+			--link-dest=${backup_previous} /tmp/${HOST} ${backup_current}
 		rync-check $?
 	else
 		echo `clock`"No previous backup detected in ${backup_host_dir}. Creating new full backup set"
-		rsync -a --stats --delete --delete-excluded --exclude-from=$exclude /tmp/${HOST} ${backup_current}
+		rsync -a --stats --delete --delete-excluded --exclude-from=$exclude \
+			/tmp/${HOST} ${backup_current}
 		rsync-check $?
 	fi
 
-	echo `clock`"Syncing filesystems..."
-	sync
+	echo `clock`"Syncing filesystems... "
+	sync; check $?
 	echo -e `clock`"Removing bind mount..."
-	umount /tmp/${HOST}
-	check $?
+	umount /tmp/${HOST}; check $?
 
 	# Clean up directories
 #	for i in `find $backup_volume/$backup_name.* -maxdepth 0 -type d`
