Changed to delete backups on failure instead of leaving half-broken backups. Now they should be retried within an hour if used with cron

diff --git a/backup-linux-incremental b/backup-linux-incremental
--- a/backup-linux-incremental
+++ b/backup-linux-incremental
@@ -24,7 +24,8 @@ DIR=`dirname $(readlink -f "$0")`
 clock () { echo -n "[`date +%H:%M:%S`] "; }
 function rsync-check {
 	[[ $1 == 0 ]] && echo `clock`"Rsync finished Successfully"
-	[[ $1 != 0 ]] && echo `clock`"Rsync failed with error code $1, backup for $DATE may be corrupt."
+	[[ $1 != 0 ]] && echo `clock`"Rsync failed with error code $1, backup for $DATE will be deleted."
+	return 1
 }
 
 function remove-backup {
@@ -73,7 +74,7 @@ if flock -xn 200; then
 	backup_host_dir="$BACKUPDIR/$target"
 	backup_current="$backup_host_dir/$DATE"
 	exclude=$backup_host_dir/_exclude
-	exclude2=/tmp/_exclude
+	exclude2=/tmp/$(basename "$0")_exclude
 	cleanup=$backup_host_dir/_cleanup
 
 	if [ ! -f $exclude ]
@@ -117,13 +118,15 @@ EOF
 	then
 		echo `clock`"Using $backup_previous for hardlinks"
 		rsync -aAXH --stats --delete --delete-excluded --exclude-from=$exclude \
-			--exclude-from=$exclude2 --link-dest=$backup_previous $target:/ "$backup_current"
+			--exclude-from=$exclude2 --link-dest="$backup_previous" $target:/ "$backup_current"
 		rsync-check $?
+		[[ $? != 0 ]] && rm -rf "$backup_current"
 	else
 		echo `clock`"No previous backup detected in $backup_host_dir. Creating new full backup set"
 		rsync -aAXH --stats --delete --delete-excluded --exclude-from=$exclude \
 			--exclude-from=$exclude2 $target:/ "$backup_current"
 		rsync-check $?
+		[[ $? ! 0 ]] && rm -rf "$backup_current"
 	fi
 
 	#Touching backup folder to set completion time
