Changed to ok/fail function

diff --git a/backup-system b/backup-system
--- a/backup-system
+++ b/backup-system
@@ -1,4 +1,4 @@
-#!/bin/zsh
+#!/bin/bash
 
 BACKUPDIR=/raid/shares/backups/Linux
 DATE=`date +%Y-%m-%d`
@@ -11,6 +11,11 @@ if [ $# -lt 1 ] ; then
 	exit 1
 fi
 
+function check {
+	[[ $1 == 0 ]] && echo -e "[\e[1;32mOK\e[00m]"
+	[[ $1 != 0 ]] && echo -e "[\e[1;31mFAILED\e[00m]\nSee ${LOG} for more details"
+}
+
 echo "" > ${LOG}
 
 for var in $@
@@ -19,15 +24,11 @@ do
 		abachi)
 			echo -n "${DATE} Backing up abachi... "
 			dd if=`mount|grep "on / type"|grep -o "/dev/sd[a-z]"` of=${BACKUPDIR}/abachi.img.${DATE} bs=1M 2>>${LOG}
-			rc=$?
-			[[ $rc == 0 ]] && echo -e "[\e[1;32mOK\e[00m]"
-			[[ $rc != 0 ]] && echo -e "[\e[1;31mFAILED\e[00m]\nSee ${LOG} for more details";;
+			check $?;;
 		bloodwood|birch|mahogany)
 			echo -n "Backing up ${var}..."
 			cp /raid/virtual-machines/${var}.qed ${BACKUPDIR}/${var}.qed.${DATE} 2>>${LOG}
-			rc=$?
-			[[ $rc == 0 ]] && echo -e "[\e[1;32mOK\e[00m]"
-			[[ $rc != 0 ]] && echo -e "[\e[1;31mFAILED\e[00m]\nSee ${LOG} for more details";;
+			check $?;;
 		*) echo "${var} is unknown; skipping."
 	esac
 done
