Added armv7 support to dlaur/build-new-packages

diff --git a/dlaur b/dlaur
--- a/dlaur
+++ b/dlaur
@@ -9,45 +9,41 @@ fi
 
 if [[ $1 == '--help' ]]
 then
-	echo "USAGE: $(basename $0) [--build] package 1 [package 2] [package N]"
+	echo "USAGE: $(basename $0) package 1 [package 2] [package N]"
 	exit 0
 fi
 
-if echo $@|grep -q '\-\-build'
-then
-	build=true
-	packages=$(echo $@|sed 's/--build//g')
+[[ $(uname -m) == "armv7l" ]] && yaourt=1
+
+packages=$@
+
+if [[ ! -z "$yaourt" ]]; then
+	for pkg in $packages
+	do
+		rm -rf $pkg
+		yaourt -G $pkg 2> /dev/null
+	done
+
 else
-	packages=$@
+	startdir=$(pwd)
+	tmp=$(mktemp -d)
+	[[ $? != 0 ]] && echo "An error has occurred while creating a temp directory! Aborting..." && exit 1
+	cd $tmp
+	aura -Aw $packages
+	for i in $packages
+	do
+		cd "$tmp"
+		test=$(ls $i*)
+		if [[ -z $test ]]
+		then
+			echo "Package $i was not found"
+		else
+			tar xf "$tmp/$i"*.tar.gz
+			rm -rf "$tmp/$i"*.tar.gz
+		fi
+	done
+
+	[[ -z "$2" ]] && [[ -z "$test" ]] && exit 1
+	mv $tmp/* "$startdir"
+	rm -rf "$tmp"
 fi
-
-
-startdir=$(pwd)
-tmp=$(mktemp -d)
-[[ $? != 0 ]] && echo "An error has occurred while creating a temp directory! Aborting..." && exit 1
-cd $tmp
-aura -Aw $packages
-for i in $packages
-do
-	cd "$tmp"
-	test=$(ls $i*)
-	if [[ -z $test ]]
-	then
-		echo "Package $i was not found"
-	else
-	tar xf "$tmp/$i"*.tar.gz
-	rm -rf "$tmp/$i"*.tar.gz
-
-	if [[ ! -z "$build" ]]
-	then
-		cd "$tmp/$i"
-		makepkg -rcfs
-		mv *.pkg.tar* "$tmp"
-		rm -rf "$tmp/$i"
-	fi
-fi
-done
-
-[[ -z "$2" ]] && [[ -z "$test" ]] && exit 1
-mv $tmp/* "$startdir"
-rm -rf "$tmp"
