Added some minor error checking

diff --git a/dlaur b/dlaur
--- a/dlaur
+++ b/dlaur
@@ -30,6 +30,11 @@ aura -Aw $packages
 for i in $packages
 do
 	cd "$tmp"
+	test=$(ls $i)
+	if [[ -z $test ]]
+	then
+		echo "Package $i was not found"
+	else
 	tar xf "$tmp/$i"*.tar.gz
 	rm -rf "$tmp/$i"*.tar.gz
 
@@ -40,7 +45,9 @@ do
 		mv *.pkg.tar* "$tmp"
 		rm -rf "$tmp/$i"
 	fi
+fi
 done
 
+[[ -z "$2" ]] && [[ -z "$test" ]] && exit 1
 mv $tmp/* "$startdir"
 rm -rf "$tmp"
