Change lib sourcing to work from any location; changed block device check; changed debugging to not throw an error when disabled;

diff --git a/restore-abachi-incremental b/restore-abachi-incremental
--- a/restore-abachi-incremental
+++ b/restore-abachi-incremental
@@ -1,4 +1,4 @@
-#!/bin/zsh
+#!/bin/bash
 
 HOST="abachi"
 BACKUPDIR=/raid/shares/backups/Linux
@@ -25,7 +25,10 @@ fi
 
 
 # Functions
-. lib/check
+DIR="${BASH_SOURCE%/*}"
+if [[ ! -d "${DIR}" ]]; then DIR="${PWD}"; fi
+. ${DIR}/lib/check
+
 clock () { echo -n "[`date +%H:%M:%S`] "; }
 function rsync-check {
 	[[ $1 == 0 ]] && echo `clock`"Rsync finished Successfully"
@@ -55,9 +58,9 @@ if flock -xn 200; then
 		exit 1
 	fi
 
-	if [ ! -b ${restore_destination} ]
+	if [ ! -b ${restore_device} ]
 	then
-		echo "${DATE} Desatination '${restore_device}' does not appear to be a block device! Aborting"
+		echo "${DATE} Destination '${restore_device}' does not appear to be a block device! Aborting"
 		exit 1
 	fi
 
@@ -74,19 +77,19 @@ if flock -xn 200; then
 	echo "Restore Destination Device: ${restore_device}"
 	echo "Current partition table on destination device:"
 	fdisk -l ${restore_device}
+	echo
 	echo "All data at the restore destination will be deleted!"
-	echo "Press enter to continue (or ctrl+c to cancel)... DO NOT CONTINUE YES!! *UNFINISHED*"
+	echo "Press enter to continue (or ctrl+c to cancel)..."
 	read
-	exit 1
 
 	echo -n `clock`"Creating new partition table on ${restore_device}... "
 	parted -s ${restore_device} mklabel msdos
 	check $? quit
 	echo -n `clock`"Creating new root partition on ${restore_device}... "
-	(echo n; echo p; echo 1; echo ; echo ; echo w) | fdisk ${restore_device}
+	(echo n; echo p; echo 1; echo ; echo ; echo w) | fdisk ${restore_device} > /dev/null
 	check $? quit
 
-	if [ ${DEBUG} == 0 ]
+	if [ "${DEBUG}x" == "0x" ] > /dev/null
 	then
 		echo "New partition table:"
 		fdisk -l ${restore_device}
@@ -95,27 +98,36 @@ if flock -xn 200; then
 	fi
 
 	echo -n `clock`"Creating filesystem... "
-	mkfs.ext4 -m 0 -L ${HOST}-root ${restore_device}1
+	mkfs.ext4 -m 0 -L ${HOST}-root ${restore_device}1 > /dev/null
 	check $? quit
+	[[ ${DEBUG} == 0 ]] && read
 
 	echo -n `clock`"Mounting restore device... "
 	mkdir -p ${restore_destination}
 	umount ${restore_destination} > /dev/null 2>&1
 	mount ${restore_device}1 ${restore_destination}
 	check $? quit
+	[[ ${DEBUG} == 0 ]] && read
 
 	echo -n `clock`"Restoring files... "
-	rsync -aH --stats ${restore_source} ${restore_destination}
+#	rsync -aH --stats ${restore_source}/ ${restore_destination}
 	rsync-check $?
-
-	echo `clock`"Making device bootable..."
-	arch-chroot ${restore_destination} syslinux-install_update -iam
+	[[ ${DEBUG} == 0 ]] && read
 
 	echo -n `clock`"Syncing filesystems... "
 	sync; check $?
+	[[ ${DEBUG} == 0 ]] && read
+
+	echo `clock`"Making device bootable..."
+#	arch-chroot ${restore_destination} syslinux-install_update -iam
+	[[ ${DEBUG} == 0 ]] && read
 
 	echo -n `clock`"Unmounting ${restore_device}... "
-	unmount ${restore_destination} > /dev/null 2>&1
+	umount ${restore_destination} > /dev/null 2>&1
+	check $?
+
+	echo -n `clocl`"Cleaning up mount point... "
+	rmdir ${restore_destination} > /dev/null 2>&1
 	check $?
 
 	echo `clock`"Restore completed!"
